// Code generated by protoc-gen-go. DO NOT EDIT.
// source: bookingStub/booking.proto

package Booking

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Section int32

const (
	Section_A Section = 0
	Section_B Section = 1
)

var Section_name = map[int32]string{
	0: "A",
	1: "B",
}

var Section_value = map[string]int32{
	"A": 0,
	"B": 1,
}

func (x Section) String() string {
	return proto.EnumName(Section_name, int32(x))
}

func (Section) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d9eaade48d932940, []int{0}
}

type Sections struct {
	//value can be either of A or B
	Section              Section  `protobuf:"varint,1,opt,name=section,proto3,enum=Booking.Section" json:"section,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sections) Reset()         { *m = Sections{} }
func (m *Sections) String() string { return proto.CompactTextString(m) }
func (*Sections) ProtoMessage()    {}
func (*Sections) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9eaade48d932940, []int{0}
}

func (m *Sections) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sections.Unmarshal(m, b)
}
func (m *Sections) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sections.Marshal(b, m, deterministic)
}
func (m *Sections) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sections.Merge(m, src)
}
func (m *Sections) XXX_Size() int {
	return xxx_messageInfo_Sections.Size(m)
}
func (m *Sections) XXX_DiscardUnknown() {
	xxx_messageInfo_Sections.DiscardUnknown(m)
}

var xxx_messageInfo_Sections proto.InternalMessageInfo

func (m *Sections) GetSection() Section {
	if m != nil {
		return m.Section
	}
	return Section_A
}

type User struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Id                   int64    `protobuf:"varint,4,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9eaade48d932940, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type Travel struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Cost                 float64  `protobuf:"fixed64,3,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Travel) Reset()         { *m = Travel{} }
func (m *Travel) String() string { return proto.CompactTextString(m) }
func (*Travel) ProtoMessage()    {}
func (*Travel) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9eaade48d932940, []int{2}
}

func (m *Travel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Travel.Unmarshal(m, b)
}
func (m *Travel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Travel.Marshal(b, m, deterministic)
}
func (m *Travel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Travel.Merge(m, src)
}
func (m *Travel) XXX_Size() int {
	return xxx_messageInfo_Travel.Size(m)
}
func (m *Travel) XXX_DiscardUnknown() {
	xxx_messageInfo_Travel.DiscardUnknown(m)
}

var xxx_messageInfo_Travel proto.InternalMessageInfo

func (m *Travel) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Travel) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Travel) GetCost() float64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

type BookingRequest struct {
	UserId               int64     `protobuf:"varint,1,opt,name=UserId,proto3" json:"UserId,omitempty"`
	TrainNum             int32     `protobuf:"varint,2,opt,name=TrainNum,proto3" json:"TrainNum,omitempty"`
	SourceStation        string    `protobuf:"bytes,3,opt,name=SourceStation,proto3" json:"SourceStation,omitempty"`
	DestinationStation   string    `protobuf:"bytes,4,opt,name=DestinationStation,proto3" json:"DestinationStation,omitempty"`
	Date                 string    `protobuf:"bytes,5,opt,name=date,proto3" json:"date,omitempty"`
	Section              *Sections `protobuf:"bytes,6,opt,name=section,proto3" json:"section,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *BookingRequest) Reset()         { *m = BookingRequest{} }
func (m *BookingRequest) String() string { return proto.CompactTextString(m) }
func (*BookingRequest) ProtoMessage()    {}
func (*BookingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9eaade48d932940, []int{3}
}

func (m *BookingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingRequest.Unmarshal(m, b)
}
func (m *BookingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingRequest.Marshal(b, m, deterministic)
}
func (m *BookingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingRequest.Merge(m, src)
}
func (m *BookingRequest) XXX_Size() int {
	return xxx_messageInfo_BookingRequest.Size(m)
}
func (m *BookingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookingRequest proto.InternalMessageInfo

func (m *BookingRequest) GetUserId() int64 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BookingRequest) GetTrainNum() int32 {
	if m != nil {
		return m.TrainNum
	}
	return 0
}

func (m *BookingRequest) GetSourceStation() string {
	if m != nil {
		return m.SourceStation
	}
	return ""
}

func (m *BookingRequest) GetDestinationStation() string {
	if m != nil {
		return m.DestinationStation
	}
	return ""
}

func (m *BookingRequest) GetDate() string {
	if m != nil {
		return m.Date
	}
	return ""
}

func (m *BookingRequest) GetSection() *Sections {
	if m != nil {
		return m.Section
	}
	return nil
}

type BookingResponse struct {
	BookingId            int64    `protobuf:"varint,1,opt,name=bookingId,proto3" json:"bookingId,omitempty"`
	SeatNumber           int32    `protobuf:"varint,2,opt,name=seatNumber,proto3" json:"seatNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingResponse) Reset()         { *m = BookingResponse{} }
func (m *BookingResponse) String() string { return proto.CompactTextString(m) }
func (*BookingResponse) ProtoMessage()    {}
func (*BookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9eaade48d932940, []int{4}
}

func (m *BookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingResponse.Unmarshal(m, b)
}
func (m *BookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingResponse.Marshal(b, m, deterministic)
}
func (m *BookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingResponse.Merge(m, src)
}
func (m *BookingResponse) XXX_Size() int {
	return xxx_messageInfo_BookingResponse.Size(m)
}
func (m *BookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookingResponse proto.InternalMessageInfo

func (m *BookingResponse) GetBookingId() int64 {
	if m != nil {
		return m.BookingId
	}
	return 0
}

func (m *BookingResponse) GetSeatNumber() int32 {
	if m != nil {
		return m.SeatNumber
	}
	return 0
}

type BookingsResponse struct {
	Bookings             []*BookingResponse `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BookingsResponse) Reset()         { *m = BookingsResponse{} }
func (m *BookingsResponse) String() string { return proto.CompactTextString(m) }
func (*BookingsResponse) ProtoMessage()    {}
func (*BookingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9eaade48d932940, []int{5}
}

func (m *BookingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingsResponse.Unmarshal(m, b)
}
func (m *BookingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingsResponse.Marshal(b, m, deterministic)
}
func (m *BookingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingsResponse.Merge(m, src)
}
func (m *BookingsResponse) XXX_Size() int {
	return xxx_messageInfo_BookingsResponse.Size(m)
}
func (m *BookingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookingsResponse proto.InternalMessageInfo

func (m *BookingsResponse) GetBookings() []*BookingResponse {
	if m != nil {
		return m.Bookings
	}
	return nil
}

type DeleteBookingRequest struct {
	UesrId               int64    `protobuf:"varint,1,opt,name=uesrId,proto3" json:"uesrId,omitempty"`
	BookingId            int64    `protobuf:"varint,2,opt,name=bookingId,proto3" json:"bookingId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookingRequest) Reset()         { *m = DeleteBookingRequest{} }
func (m *DeleteBookingRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBookingRequest) ProtoMessage()    {}
func (*DeleteBookingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9eaade48d932940, []int{6}
}

func (m *DeleteBookingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookingRequest.Unmarshal(m, b)
}
func (m *DeleteBookingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookingRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBookingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookingRequest.Merge(m, src)
}
func (m *DeleteBookingRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBookingRequest.Size(m)
}
func (m *DeleteBookingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookingRequest proto.InternalMessageInfo

func (m *DeleteBookingRequest) GetUesrId() int64 {
	if m != nil {
		return m.UesrId
	}
	return 0
}

func (m *DeleteBookingRequest) GetBookingId() int64 {
	if m != nil {
		return m.BookingId
	}
	return 0
}

type DeleteBookingResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookingResponse) Reset()         { *m = DeleteBookingResponse{} }
func (m *DeleteBookingResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteBookingResponse) ProtoMessage()    {}
func (*DeleteBookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9eaade48d932940, []int{7}
}

func (m *DeleteBookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookingResponse.Unmarshal(m, b)
}
func (m *DeleteBookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookingResponse.Marshal(b, m, deterministic)
}
func (m *DeleteBookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookingResponse.Merge(m, src)
}
func (m *DeleteBookingResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteBookingResponse.Size(m)
}
func (m *DeleteBookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookingResponse proto.InternalMessageInfo

func (m *DeleteBookingResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type BookingReceipt struct {
	BookingId            int64    `protobuf:"varint,1,opt,name=BookingId,proto3" json:"BookingId,omitempty"`
	UserId               int32    `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
	SrcStation           string   `protobuf:"bytes,3,opt,name=SrcStation,proto3" json:"SrcStation,omitempty"`
	DestStation          string   `protobuf:"bytes,4,opt,name=DestStation,proto3" json:"DestStation,omitempty"`
	TrainNumber          int32    `protobuf:"varint,5,opt,name=TrainNumber,proto3" json:"TrainNumber,omitempty"`
	SeatNum              int32    `protobuf:"varint,6,opt,name=SeatNum,proto3" json:"SeatNum,omitempty"`
	Price                float32  `protobuf:"fixed32,7,opt,name=Price,proto3" json:"Price,omitempty"`
	Section              int32    `protobuf:"varint,8,opt,name=Section,proto3" json:"Section,omitempty"`
	FirstName            string   `protobuf:"bytes,9,opt,name=FirstName,proto3" json:"FirstName,omitempty"`
	LastName             string   `protobuf:"bytes,10,opt,name=LastName,proto3" json:"LastName,omitempty"`
	Email                string   `protobuf:"bytes,11,opt,name=Email,proto3" json:"Email,omitempty"`
	Status               string   `protobuf:"bytes,12,opt,name=Status,proto3" json:"Status,omitempty"`
	BookingDateTime      string   `protobuf:"bytes,13,opt,name=BookingDateTime,proto3" json:"BookingDateTime,omitempty"`
	ModifiedDateTime     string   `protobuf:"bytes,14,opt,name=ModifiedDateTime,proto3" json:"ModifiedDateTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingReceipt) Reset()         { *m = BookingReceipt{} }
func (m *BookingReceipt) String() string { return proto.CompactTextString(m) }
func (*BookingReceipt) ProtoMessage()    {}
func (*BookingReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9eaade48d932940, []int{8}
}

func (m *BookingReceipt) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingReceipt.Unmarshal(m, b)
}
func (m *BookingReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingReceipt.Marshal(b, m, deterministic)
}
func (m *BookingReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingReceipt.Merge(m, src)
}
func (m *BookingReceipt) XXX_Size() int {
	return xxx_messageInfo_BookingReceipt.Size(m)
}
func (m *BookingReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_BookingReceipt proto.InternalMessageInfo

func (m *BookingReceipt) GetBookingId() int64 {
	if m != nil {
		return m.BookingId
	}
	return 0
}

func (m *BookingReceipt) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *BookingReceipt) GetSrcStation() string {
	if m != nil {
		return m.SrcStation
	}
	return ""
}

func (m *BookingReceipt) GetDestStation() string {
	if m != nil {
		return m.DestStation
	}
	return ""
}

func (m *BookingReceipt) GetTrainNumber() int32 {
	if m != nil {
		return m.TrainNumber
	}
	return 0
}

func (m *BookingReceipt) GetSeatNum() int32 {
	if m != nil {
		return m.SeatNum
	}
	return 0
}

func (m *BookingReceipt) GetPrice() float32 {
	if m != nil {
		return m.Price
	}
	return 0
}

func (m *BookingReceipt) GetSection() int32 {
	if m != nil {
		return m.Section
	}
	return 0
}

func (m *BookingReceipt) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *BookingReceipt) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *BookingReceipt) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *BookingReceipt) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *BookingReceipt) GetBookingDateTime() string {
	if m != nil {
		return m.BookingDateTime
	}
	return ""
}

func (m *BookingReceipt) GetModifiedDateTime() string {
	if m != nil {
		return m.ModifiedDateTime
	}
	return ""
}

type BookingReceipts struct {
	Receipts             []*BookingReceipt `protobuf:"bytes,1,rep,name=receipts,proto3" json:"receipts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *BookingReceipts) Reset()         { *m = BookingReceipts{} }
func (m *BookingReceipts) String() string { return proto.CompactTextString(m) }
func (*BookingReceipts) ProtoMessage()    {}
func (*BookingReceipts) Descriptor() ([]byte, []int) {
	return fileDescriptor_d9eaade48d932940, []int{9}
}

func (m *BookingReceipts) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingReceipts.Unmarshal(m, b)
}
func (m *BookingReceipts) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingReceipts.Marshal(b, m, deterministic)
}
func (m *BookingReceipts) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingReceipts.Merge(m, src)
}
func (m *BookingReceipts) XXX_Size() int {
	return xxx_messageInfo_BookingReceipts.Size(m)
}
func (m *BookingReceipts) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingReceipts.DiscardUnknown(m)
}

var xxx_messageInfo_BookingReceipts proto.InternalMessageInfo

func (m *BookingReceipts) GetReceipts() []*BookingReceipt {
	if m != nil {
		return m.Receipts
	}
	return nil
}

func init() {
	proto.RegisterEnum("Booking.Section", Section_name, Section_value)
	proto.RegisterType((*Sections)(nil), "Booking.Sections")
	proto.RegisterType((*User)(nil), "Booking.User")
	proto.RegisterType((*Travel)(nil), "Booking.Travel")
	proto.RegisterType((*BookingRequest)(nil), "Booking.BookingRequest")
	proto.RegisterType((*BookingResponse)(nil), "Booking.BookingResponse")
	proto.RegisterType((*BookingsResponse)(nil), "Booking.BookingsResponse")
	proto.RegisterType((*DeleteBookingRequest)(nil), "Booking.DeleteBookingRequest")
	proto.RegisterType((*DeleteBookingResponse)(nil), "Booking.DeleteBookingResponse")
	proto.RegisterType((*BookingReceipt)(nil), "Booking.BookingReceipt")
	proto.RegisterType((*BookingReceipts)(nil), "Booking.BookingReceipts")
}

func init() { proto.RegisterFile("bookingStub/booking.proto", fileDescriptor_d9eaade48d932940) }

var fileDescriptor_d9eaade48d932940 = []byte{
	// 687 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xcd, 0x6e, 0xd3, 0x4c,
	0x14, 0xad, 0xf3, 0x9f, 0x9b, 0x2f, 0xf9, 0xc2, 0xa8, 0xb4, 0x6e, 0x05, 0x55, 0x64, 0xb1, 0x88,
	0x8a, 0x14, 0x44, 0x8a, 0xd8, 0xb0, 0x81, 0x10, 0x5a, 0x40, 0x6d, 0x01, 0xbb, 0xdd, 0xb0, 0x73,
	0xec, 0x1b, 0x34, 0x22, 0xc9, 0x84, 0x99, 0x71, 0x1f, 0x82, 0xc7, 0xe1, 0x75, 0x78, 0x19, 0x34,
	0x3f, 0x9e, 0x38, 0x6e, 0xbb, 0x40, 0xac, 0x3a, 0xe7, 0xde, 0x93, 0xe3, 0xfb, 0x73, 0xae, 0x0a,
	0x07, 0x33, 0xc6, 0xbe, 0xd3, 0xd5, 0xb7, 0x48, 0x66, 0xb3, 0x67, 0xf6, 0x3d, 0x5a, 0x73, 0x26,
	0x19, 0x69, 0x4e, 0x0c, 0x0c, 0x5e, 0x42, 0x2b, 0xc2, 0x44, 0x52, 0xb6, 0x12, 0xe4, 0x18, 0x9a,
	0xc2, 0xbc, 0x7d, 0x6f, 0xe0, 0x0d, 0x7b, 0xe3, 0xfe, 0xc8, 0xd2, 0x46, 0x96, 0x13, 0xe6, 0x84,
	0x60, 0x0e, 0xb5, 0x6b, 0x81, 0x9c, 0x3c, 0x82, 0xf6, 0x9c, 0x72, 0x21, 0x2f, 0xe3, 0x25, 0xea,
	0x5f, 0xb5, 0xc3, 0x4d, 0x80, 0x1c, 0x42, 0x6b, 0x11, 0xdb, 0x64, 0x45, 0x27, 0x1d, 0x26, 0xbb,
	0x50, 0xc7, 0x65, 0x4c, 0x17, 0x7e, 0x55, 0x27, 0x0c, 0x20, 0x3d, 0xa8, 0xd0, 0xd4, 0xaf, 0x0d,
	0xbc, 0x61, 0x35, 0xac, 0xd0, 0x34, 0x78, 0x0d, 0x8d, 0x2b, 0x1e, 0xdf, 0xe0, 0x82, 0x10, 0xa8,
	0xcd, 0x39, 0x5b, 0xda, 0x8f, 0xe8, 0xb7, 0x62, 0x4b, 0x66, 0x95, 0x2b, 0x92, 0x29, 0x4e, 0xc2,
	0x84, 0xd4, 0x92, 0x5e, 0xa8, 0xdf, 0xc1, 0x6f, 0x0f, 0x7a, 0xb6, 0x8d, 0x10, 0x7f, 0x64, 0x28,
	0x24, 0xd9, 0x83, 0x86, 0x2a, 0xfe, 0x43, 0xaa, 0xc5, 0xaa, 0xa1, 0x45, 0xaa, 0xdc, 0x2b, 0x1e,
	0xd3, 0xd5, 0x65, 0xb6, 0xd4, 0xa2, 0xf5, 0xd0, 0x61, 0xf2, 0x04, 0xba, 0x11, 0xcb, 0x78, 0x82,
	0x91, 0x8c, 0xf5, 0x88, 0x4c, 0xd9, 0xdb, 0x41, 0x32, 0x02, 0x32, 0x45, 0x21, 0xe9, 0x4a, 0xc3,
	0x9c, 0x5a, 0xd3, 0xd4, 0x3b, 0x32, 0xaa, 0xe0, 0x34, 0x96, 0xe8, 0xd7, 0x4d, 0x53, 0xea, 0x4d,
	0x9e, 0x6e, 0xd6, 0xd0, 0x18, 0x78, 0xc3, 0xce, 0xf8, 0x41, 0x79, 0x0d, 0x62, 0xb3, 0x87, 0x4f,
	0xf0, 0xbf, 0x6b, 0x4e, 0xac, 0xd9, 0x4a, 0xa0, 0x5a, 0x89, 0x5d, 0xb6, 0x6b, 0x70, 0x13, 0x20,
	0x47, 0x00, 0x02, 0x63, 0x79, 0x99, 0x2d, 0x67, 0xc8, 0x6d, 0x97, 0x85, 0x48, 0xf0, 0x1e, 0xfa,
	0x56, 0x50, 0x38, 0xc5, 0x17, 0xd0, 0xb2, 0x02, 0xc2, 0xf7, 0x06, 0xd5, 0x61, 0x67, 0xec, 0xbb,
	0x92, 0x4a, 0x5f, 0x0f, 0x1d, 0x33, 0x38, 0x87, 0xdd, 0x29, 0x2e, 0x50, 0xe2, 0xed, 0xe9, 0x67,
	0x28, 0x0a, 0xd3, 0x37, 0x68, 0xbb, 0xee, 0x4a, 0xa9, 0xee, 0xe0, 0x39, 0x3c, 0x2c, 0xa9, 0xd9,
	0xe2, 0x7c, 0x68, 0x8a, 0x2c, 0x49, 0x50, 0x08, 0xad, 0xd7, 0x0a, 0x73, 0x18, 0xfc, 0xaa, 0x16,
	0x36, 0x9f, 0x20, 0x5d, 0x4b, 0xf5, 0x8d, 0x49, 0x79, 0x36, 0x2e, 0x50, 0xf0, 0x85, 0x99, 0x4b,
	0xee, 0x8b, 0x23, 0x80, 0x88, 0x27, 0xdb, 0x8b, 0x2f, 0x44, 0xc8, 0x00, 0x3a, 0x6a, 0xb7, 0xdb,
	0xeb, 0x2e, 0x86, 0x14, 0x23, 0x77, 0x92, 0x1a, 0x7b, 0x5d, 0xcb, 0x17, 0x43, 0xaa, 0x8d, 0xc8,
	0x6c, 0x41, 0x6f, 0xbd, 0x1e, 0xe6, 0x50, 0x1d, 0xca, 0x67, 0x4e, 0x13, 0xf4, 0x9b, 0x03, 0x6f,
	0x58, 0x09, 0x0d, 0x30, 0x7c, 0xe3, 0x92, 0x56, 0xce, 0xd7, 0x50, 0xf5, 0x78, 0xea, 0x4e, 0xb2,
	0x6d, 0x4e, 0xf2, 0xb4, 0x78, 0x92, 0xe7, 0xf9, 0x49, 0x82, 0x39, 0xc9, 0xf3, 0xc2, 0x49, 0xbe,
	0xd3, 0x27, 0xd9, 0x31, 0x27, 0xa9, 0x81, 0x9a, 0x8a, 0x6a, 0x23, 0x13, 0xfe, 0x7f, 0x3a, 0x6c,
	0x11, 0x19, 0x3a, 0xeb, 0x4d, 0x63, 0x89, 0x57, 0x74, 0x89, 0x7e, 0x57, 0x13, 0xca, 0x61, 0x72,
	0x0c, 0xfd, 0x0b, 0x96, 0xd2, 0x39, 0xc5, 0xd4, 0x51, 0x7b, 0x9a, 0x7a, 0x2b, 0x1e, 0x9c, 0x16,
	0x0c, 0xad, 0x77, 0x26, 0xc8, 0x09, 0xb4, 0xb8, 0x7d, 0x5b, 0xfb, 0xed, 0xdf, 0xb6, 0x9f, 0xce,
	0x87, 0x8e, 0x78, 0xbc, 0xef, 0xe6, 0x43, 0xea, 0xe0, 0xbd, 0xe9, 0xef, 0xa8, 0x3f, 0x93, 0xbe,
	0x37, 0xfe, 0xb9, 0x71, 0x45, 0x84, 0xfc, 0x46, 0xcd, 0x72, 0x0a, 0xdd, 0xb7, 0x1c, 0x63, 0xe7,
	0x2d, 0x72, 0x87, 0xbe, 0xf6, 0xee, 0xe1, 0xbd, 0xbe, 0x0f, 0x76, 0xc8, 0x05, 0xec, 0x9d, 0xa1,
	0x54, 0x96, 0x29, 0x37, 0xf0, 0x37, 0x72, 0xe6, 0x27, 0xc1, 0x0e, 0xf9, 0x08, 0xe4, 0x0c, 0xa5,
	0xed, 0x21, 0x3f, 0xc9, 0xfb, 0xa5, 0x0e, 0xca, 0x09, 0x51, 0x28, 0x6d, 0x0a, 0xdd, 0xeb, 0x75,
	0xfa, 0xaf, 0x0d, 0x7e, 0x81, 0xde, 0xd6, 0x09, 0x0a, 0xf2, 0xd8, 0xb1, 0xef, 0xba, 0xf4, 0xc3,
	0xa3, 0xfb, 0xd2, 0xb9, 0xe4, 0xa4, 0xf3, 0xb5, 0x3d, 0x7a, 0x65, 0xc3, 0xb3, 0x86, 0xfe, 0xdf,
	0x74, 0xf2, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc1, 0xca, 0x9b, 0x12, 0xb8, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookingServiceClient is the client API for BookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookingServiceClient interface {
	// returns pair of bookingId, seatNum
	CreateBooking(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*BookingResponse, error)
	// returns array of pairs{ bookingId, seatNum}
	GetUserBookingReceipts(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*BookingReceipts, error)
	// returns array of pairs{ bookingId, seatNum}
	GetSectionBookings(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*BookingsResponse, error)
	//can update user details only
	UpdateBooking(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*BookingResponse, error)
	DeleteBookings(ctx context.Context, in *DeleteBookingRequest, opts ...grpc.CallOption) (*DeleteBookingResponse, error)
}

type bookingServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookingServiceClient(cc *grpc.ClientConn) BookingServiceClient {
	return &bookingServiceClient{cc}
}

func (c *bookingServiceClient) CreateBooking(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*BookingResponse, error) {
	out := new(BookingResponse)
	err := c.cc.Invoke(ctx, "/Booking.BookingService/CreateBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) GetUserBookingReceipts(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*BookingReceipts, error) {
	out := new(BookingReceipts)
	err := c.cc.Invoke(ctx, "/Booking.BookingService/GetUserBookingReceipts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) GetSectionBookings(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*BookingsResponse, error) {
	out := new(BookingsResponse)
	err := c.cc.Invoke(ctx, "/Booking.BookingService/GetSectionBookings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) UpdateBooking(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*BookingResponse, error) {
	out := new(BookingResponse)
	err := c.cc.Invoke(ctx, "/Booking.BookingService/UpdateBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) DeleteBookings(ctx context.Context, in *DeleteBookingRequest, opts ...grpc.CallOption) (*DeleteBookingResponse, error) {
	out := new(DeleteBookingResponse)
	err := c.cc.Invoke(ctx, "/Booking.BookingService/DeleteBookings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingServiceServer is the server API for BookingService service.
type BookingServiceServer interface {
	// returns pair of bookingId, seatNum
	CreateBooking(context.Context, *BookingRequest) (*BookingResponse, error)
	// returns array of pairs{ bookingId, seatNum}
	GetUserBookingReceipts(context.Context, *BookingRequest) (*BookingReceipts, error)
	// returns array of pairs{ bookingId, seatNum}
	GetSectionBookings(context.Context, *BookingRequest) (*BookingsResponse, error)
	//can update user details only
	UpdateBooking(context.Context, *BookingRequest) (*BookingResponse, error)
	DeleteBookings(context.Context, *DeleteBookingRequest) (*DeleteBookingResponse, error)
}

// UnimplementedBookingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookingServiceServer struct {
}

func (*UnimplementedBookingServiceServer) CreateBooking(ctx context.Context, req *BookingRequest) (*BookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBooking not implemented")
}
func (*UnimplementedBookingServiceServer) GetUserBookingReceipts(ctx context.Context, req *BookingRequest) (*BookingReceipts, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBookingReceipts not implemented")
}
func (*UnimplementedBookingServiceServer) GetSectionBookings(ctx context.Context, req *BookingRequest) (*BookingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSectionBookings not implemented")
}
func (*UnimplementedBookingServiceServer) UpdateBooking(ctx context.Context, req *BookingRequest) (*BookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBooking not implemented")
}
func (*UnimplementedBookingServiceServer) DeleteBookings(ctx context.Context, req *DeleteBookingRequest) (*DeleteBookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBookings not implemented")
}

func RegisterBookingServiceServer(s *grpc.Server, srv BookingServiceServer) {
	s.RegisterService(&_BookingService_serviceDesc, srv)
}

func _BookingService_CreateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).CreateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking.BookingService/CreateBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).CreateBooking(ctx, req.(*BookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_GetUserBookingReceipts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).GetUserBookingReceipts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking.BookingService/GetUserBookingReceipts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).GetUserBookingReceipts(ctx, req.(*BookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_GetSectionBookings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).GetSectionBookings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking.BookingService/GetSectionBookings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).GetSectionBookings(ctx, req.(*BookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_UpdateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).UpdateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking.BookingService/UpdateBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).UpdateBooking(ctx, req.(*BookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_DeleteBookings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).DeleteBookings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking.BookingService/DeleteBookings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).DeleteBookings(ctx, req.(*DeleteBookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Booking.BookingService",
	HandlerType: (*BookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBooking",
			Handler:    _BookingService_CreateBooking_Handler,
		},
		{
			MethodName: "GetUserBookingReceipts",
			Handler:    _BookingService_GetUserBookingReceipts_Handler,
		},
		{
			MethodName: "GetSectionBookings",
			Handler:    _BookingService_GetSectionBookings_Handler,
		},
		{
			MethodName: "UpdateBooking",
			Handler:    _BookingService_UpdateBooking_Handler,
		},
		{
			MethodName: "DeleteBookings",
			Handler:    _BookingService_DeleteBookings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "bookingStub/booking.proto",
}
