// Code generated by protoc-gen-go. DO NOT EDIT.
// source: BookingStub/booking.proto

package Booking

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Section int32

const (
	Section_A Section = 0
	Section_B Section = 1
)

var Section_name = map[int32]string{
	0: "A",
	1: "B",
}

var Section_value = map[string]int32{
	"A": 0,
	"B": 1,
}

func (x Section) String() string {
	return proto.EnumName(Section_name, int32(x))
}

func (Section) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_18ce09db44fa9590, []int{0}
}

type Sections struct {
	//value can be either of A or B
	Section              Section  `protobuf:"varint,1,opt,name=section,proto3,enum=Booking.Section" json:"section,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Sections) Reset()         { *m = Sections{} }
func (m *Sections) String() string { return proto.CompactTextString(m) }
func (*Sections) ProtoMessage()    {}
func (*Sections) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ce09db44fa9590, []int{0}
}

func (m *Sections) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Sections.Unmarshal(m, b)
}
func (m *Sections) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Sections.Marshal(b, m, deterministic)
}
func (m *Sections) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Sections.Merge(m, src)
}
func (m *Sections) XXX_Size() int {
	return xxx_messageInfo_Sections.Size(m)
}
func (m *Sections) XXX_DiscardUnknown() {
	xxx_messageInfo_Sections.DiscardUnknown(m)
}

var xxx_messageInfo_Sections proto.InternalMessageInfo

func (m *Sections) GetSection() Section {
	if m != nil {
		return m.Section
	}
	return Section_A
}

type User struct {
	FirstName            string   `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName             string   `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ce09db44fa9590, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type Travel struct {
	From                 string   `protobuf:"bytes,1,opt,name=from,proto3" json:"from,omitempty"`
	To                   string   `protobuf:"bytes,2,opt,name=to,proto3" json:"to,omitempty"`
	Cost                 float64  `protobuf:"fixed64,3,opt,name=cost,proto3" json:"cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Travel) Reset()         { *m = Travel{} }
func (m *Travel) String() string { return proto.CompactTextString(m) }
func (*Travel) ProtoMessage()    {}
func (*Travel) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ce09db44fa9590, []int{2}
}

func (m *Travel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Travel.Unmarshal(m, b)
}
func (m *Travel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Travel.Marshal(b, m, deterministic)
}
func (m *Travel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Travel.Merge(m, src)
}
func (m *Travel) XXX_Size() int {
	return xxx_messageInfo_Travel.Size(m)
}
func (m *Travel) XXX_DiscardUnknown() {
	xxx_messageInfo_Travel.DiscardUnknown(m)
}

var xxx_messageInfo_Travel proto.InternalMessageInfo

func (m *Travel) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Travel) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Travel) GetCost() float64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

type BookingRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Travel               *Travel  `protobuf:"bytes,2,opt,name=travel,proto3" json:"travel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingRequest) Reset()         { *m = BookingRequest{} }
func (m *BookingRequest) String() string { return proto.CompactTextString(m) }
func (*BookingRequest) ProtoMessage()    {}
func (*BookingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ce09db44fa9590, []int{3}
}

func (m *BookingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingRequest.Unmarshal(m, b)
}
func (m *BookingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingRequest.Marshal(b, m, deterministic)
}
func (m *BookingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingRequest.Merge(m, src)
}
func (m *BookingRequest) XXX_Size() int {
	return xxx_messageInfo_BookingRequest.Size(m)
}
func (m *BookingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookingRequest proto.InternalMessageInfo

func (m *BookingRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *BookingRequest) GetTravel() *Travel {
	if m != nil {
		return m.Travel
	}
	return nil
}

type BookingResponse struct {
	BookingId            int64    `protobuf:"varint,1,opt,name=bookingId,proto3" json:"bookingId,omitempty"`
	SeatNumber           int32    `protobuf:"varint,2,opt,name=seatNumber,proto3" json:"seatNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingResponse) Reset()         { *m = BookingResponse{} }
func (m *BookingResponse) String() string { return proto.CompactTextString(m) }
func (*BookingResponse) ProtoMessage()    {}
func (*BookingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ce09db44fa9590, []int{4}
}

func (m *BookingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingResponse.Unmarshal(m, b)
}
func (m *BookingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingResponse.Marshal(b, m, deterministic)
}
func (m *BookingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingResponse.Merge(m, src)
}
func (m *BookingResponse) XXX_Size() int {
	return xxx_messageInfo_BookingResponse.Size(m)
}
func (m *BookingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookingResponse proto.InternalMessageInfo

func (m *BookingResponse) GetBookingId() int64 {
	if m != nil {
		return m.BookingId
	}
	return 0
}

func (m *BookingResponse) GetSeatNumber() int32 {
	if m != nil {
		return m.SeatNumber
	}
	return 0
}

type BookingsResponse struct {
	Bookings             []*BookingResponse `protobuf:"bytes,1,rep,name=bookings,proto3" json:"bookings,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *BookingsResponse) Reset()         { *m = BookingsResponse{} }
func (m *BookingsResponse) String() string { return proto.CompactTextString(m) }
func (*BookingsResponse) ProtoMessage()    {}
func (*BookingsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_18ce09db44fa9590, []int{5}
}

func (m *BookingsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingsResponse.Unmarshal(m, b)
}
func (m *BookingsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingsResponse.Marshal(b, m, deterministic)
}
func (m *BookingsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingsResponse.Merge(m, src)
}
func (m *BookingsResponse) XXX_Size() int {
	return xxx_messageInfo_BookingsResponse.Size(m)
}
func (m *BookingsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BookingsResponse proto.InternalMessageInfo

func (m *BookingsResponse) GetBookings() []*BookingResponse {
	if m != nil {
		return m.Bookings
	}
	return nil
}

func init() {
	proto.RegisterEnum("Booking.Section", Section_name, Section_value)
	proto.RegisterType((*Sections)(nil), "Booking.Sections")
	proto.RegisterType((*User)(nil), "Booking.User")
	proto.RegisterType((*Travel)(nil), "Booking.Travel")
	proto.RegisterType((*BookingRequest)(nil), "Booking.BookingRequest")
	proto.RegisterType((*BookingResponse)(nil), "Booking.BookingResponse")
	proto.RegisterType((*BookingsResponse)(nil), "Booking.BookingsResponse")
}

func init() { proto.RegisterFile("BookingStub/booking.proto", fileDescriptor_18ce09db44fa9590) }

var fileDescriptor_18ce09db44fa9590 = []byte{
	// 419 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xdf, 0x8b, 0xd3, 0x40,
	0x10, 0xc7, 0x2f, 0xe9, 0xef, 0x09, 0x4d, 0xe3, 0x20, 0x5c, 0xae, 0x88, 0x9c, 0x79, 0xf1, 0xb8,
	0x87, 0x08, 0x51, 0x7c, 0xf0, 0x10, 0xb4, 0x16, 0x4e, 0x5f, 0x4e, 0xd8, 0x7a, 0x3e, 0x88, 0x2f,
	0x49, 0x3b, 0x95, 0x60, 0xd2, 0xad, 0xbb, 0x9b, 0xfe, 0xa5, 0xfe, 0x41, 0x92, 0xcd, 0x76, 0x5b,
	0x23, 0x16, 0xee, 0xa9, 0xb3, 0x33, 0xdf, 0xf9, 0xcc, 0xcc, 0xb7, 0x2d, 0x5c, 0xcc, 0x38, 0xff,
	0x99, 0x6f, 0x7e, 0x2c, 0x54, 0x95, 0xbd, 0xc8, 0x9a, 0x38, 0xde, 0x0a, 0xae, 0x38, 0x0e, 0x4c,
	0x29, 0x7a, 0x0d, 0xc3, 0x05, 0x2d, 0x55, 0xce, 0x37, 0x12, 0xaf, 0x61, 0x20, 0x9b, 0x38, 0x74,
	0x2e, 0x9d, 0x2b, 0x3f, 0x09, 0x62, 0x23, 0x8b, 0x8d, 0x86, 0xed, 0x05, 0xd1, 0x57, 0xe8, 0xde,
	0x4b, 0x12, 0xf8, 0x04, 0x46, 0xeb, 0x5c, 0x48, 0x75, 0x97, 0x96, 0xa4, 0xbb, 0x46, 0xec, 0x90,
	0xc0, 0x29, 0x0c, 0x8b, 0xd4, 0x14, 0x5d, 0x5d, 0xb4, 0x6f, 0x7c, 0x0c, 0x3d, 0x2a, 0xd3, 0xbc,
	0x08, 0x3b, 0xba, 0xd0, 0x3c, 0xa2, 0x77, 0xd0, 0xff, 0x22, 0xd2, 0x1d, 0x15, 0x88, 0xd0, 0x5d,
	0x0b, 0x5e, 0x1a, 0xa8, 0x8e, 0xd1, 0x07, 0x57, 0x71, 0x43, 0x72, 0x15, 0xaf, 0x35, 0x4b, 0x2e,
	0x95, 0x46, 0x38, 0x4c, 0xc7, 0xd1, 0x77, 0xf0, 0xcd, 0xd6, 0x8c, 0x7e, 0x55, 0x24, 0x15, 0x3e,
	0x83, 0x6e, 0x25, 0x49, 0x68, 0x92, 0x97, 0x8c, 0xed, 0x51, 0xf5, 0x01, 0x4c, 0x97, 0xf0, 0x39,
	0xf4, 0x95, 0x1e, 0xab, 0xe1, 0x5e, 0x32, 0xb1, 0xa2, 0x66, 0x1b, 0x66, 0xca, 0xd1, 0x67, 0x98,
	0x58, 0xba, 0xdc, 0xf2, 0x8d, 0xa4, 0xda, 0x02, 0x63, 0xee, 0xa7, 0x95, 0x9e, 0xd1, 0x61, 0x87,
	0x04, 0x3e, 0x05, 0x90, 0x94, 0xaa, 0xbb, 0xaa, 0xcc, 0x48, 0x68, 0x7a, 0x8f, 0x1d, 0x65, 0xa2,
	0x8f, 0x10, 0x18, 0xa0, 0xb4, 0xc4, 0x57, 0x30, 0x34, 0x00, 0x19, 0x3a, 0x97, 0x9d, 0x2b, 0x2f,
	0x09, 0xed, 0x3e, 0xad, 0xe9, 0xcc, 0x2a, 0xaf, 0xcf, 0x61, 0x60, 0xbe, 0x26, 0xec, 0x81, 0xf3,
	0x3e, 0x38, 0xab, 0x3f, 0x66, 0x81, 0x93, 0xfc, 0x76, 0xad, 0x25, 0x0b, 0x12, 0xbb, 0x7c, 0x49,
	0x38, 0x87, 0xf1, 0x07, 0x41, 0xa9, 0x22, 0x93, 0xc7, 0xf3, 0x7f, 0x07, 0x68, 0xf3, 0xa6, 0xff,
	0x9d, 0x1c, 0x9d, 0xe1, 0x5b, 0x98, 0xdc, 0x92, 0xaa, 0x6d, 0xdc, 0x9f, 0x80, 0x7f, 0xbb, 0x3b,
	0xbd, 0x68, 0x77, 0xcb, 0xa3, 0xf6, 0x39, 0xe0, 0x2d, 0x29, 0xb3, 0xb3, 0x25, 0x3c, 0x6a, 0xff,
	0xe8, 0xe4, 0x69, 0xca, 0x1b, 0x18, 0xdf, 0x6f, 0x57, 0x47, 0xa7, 0xb4, 0x56, 0x38, 0x75, 0xc0,
	0x0d, 0xf8, 0x73, 0x2a, 0xc8, 0xf6, 0xca, 0x07, 0x34, 0xcf, 0xbc, 0x6f, 0xa3, 0xf8, 0xc6, 0xa4,
	0xb3, 0xbe, 0xfe, 0x5f, 0xbd, 0xfc, 0x13, 0x00, 0x00, 0xff, 0xff, 0xad, 0x85, 0xc7, 0xf9, 0x74,
	0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookingServiceClient is the client API for BookingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookingServiceClient interface {
	CreateBooking(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*BookingResponse, error)
	GetUserBookings(ctx context.Context, in *User, opts ...grpc.CallOption) (*BookingsResponse, error)
	//Returns bookings for both sections
	GetSectionBookings(ctx context.Context, in *Sections, opts ...grpc.CallOption) (*BookingsResponse, error)
	//can update user details only
	UpdateBooking(ctx context.Context, in *User, opts ...grpc.CallOption) (*BookingResponse, error)
	DeleteBookings(ctx context.Context, in *User, opts ...grpc.CallOption) (*BookingResponse, error)
}

type bookingServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookingServiceClient(cc *grpc.ClientConn) BookingServiceClient {
	return &bookingServiceClient{cc}
}

func (c *bookingServiceClient) CreateBooking(ctx context.Context, in *BookingRequest, opts ...grpc.CallOption) (*BookingResponse, error) {
	out := new(BookingResponse)
	err := c.cc.Invoke(ctx, "/Booking.BookingService/CreateBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) GetUserBookings(ctx context.Context, in *User, opts ...grpc.CallOption) (*BookingsResponse, error) {
	out := new(BookingsResponse)
	err := c.cc.Invoke(ctx, "/Booking.BookingService/GetUserBookings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) GetSectionBookings(ctx context.Context, in *Sections, opts ...grpc.CallOption) (*BookingsResponse, error) {
	out := new(BookingsResponse)
	err := c.cc.Invoke(ctx, "/Booking.BookingService/GetSectionBookings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) UpdateBooking(ctx context.Context, in *User, opts ...grpc.CallOption) (*BookingResponse, error) {
	out := new(BookingResponse)
	err := c.cc.Invoke(ctx, "/Booking.BookingService/UpdateBooking", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookingServiceClient) DeleteBookings(ctx context.Context, in *User, opts ...grpc.CallOption) (*BookingResponse, error) {
	out := new(BookingResponse)
	err := c.cc.Invoke(ctx, "/Booking.BookingService/DeleteBookings", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookingServiceServer is the server API for BookingService service.
type BookingServiceServer interface {
	CreateBooking(context.Context, *BookingRequest) (*BookingResponse, error)
	GetUserBookings(context.Context, *User) (*BookingsResponse, error)
	//Returns bookings for both sections
	GetSectionBookings(context.Context, *Sections) (*BookingsResponse, error)
	//can update user details only
	UpdateBooking(context.Context, *User) (*BookingResponse, error)
	DeleteBookings(context.Context, *User) (*BookingResponse, error)
}

// UnimplementedBookingServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookingServiceServer struct {
}

func (*UnimplementedBookingServiceServer) CreateBooking(ctx context.Context, req *BookingRequest) (*BookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBooking not implemented")
}
func (*UnimplementedBookingServiceServer) GetUserBookings(ctx context.Context, req *User) (*BookingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserBookings not implemented")
}
func (*UnimplementedBookingServiceServer) GetSectionBookings(ctx context.Context, req *Sections) (*BookingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSectionBookings not implemented")
}
func (*UnimplementedBookingServiceServer) UpdateBooking(ctx context.Context, req *User) (*BookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBooking not implemented")
}
func (*UnimplementedBookingServiceServer) DeleteBookings(ctx context.Context, req *User) (*BookingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBookings not implemented")
}

func RegisterBookingServiceServer(s *grpc.Server, srv BookingServiceServer) {
	s.RegisterService(&_BookingService_serviceDesc, srv)
}

func _BookingService_CreateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).CreateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking.BookingService/CreateBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).CreateBooking(ctx, req.(*BookingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_GetUserBookings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).GetUserBookings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking.BookingService/GetUserBookings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).GetUserBookings(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_GetSectionBookings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Sections)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).GetSectionBookings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking.BookingService/GetSectionBookings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).GetSectionBookings(ctx, req.(*Sections))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_UpdateBooking_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).UpdateBooking(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking.BookingService/UpdateBooking",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).UpdateBooking(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookingService_DeleteBookings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(User)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookingServiceServer).DeleteBookings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Booking.BookingService/DeleteBookings",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookingServiceServer).DeleteBookings(ctx, req.(*User))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Booking.BookingService",
	HandlerType: (*BookingServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBooking",
			Handler:    _BookingService_CreateBooking_Handler,
		},
		{
			MethodName: "GetUserBookings",
			Handler:    _BookingService_GetUserBookings_Handler,
		},
		{
			MethodName: "GetSectionBookings",
			Handler:    _BookingService_GetSectionBookings_Handler,
		},
		{
			MethodName: "UpdateBooking",
			Handler:    _BookingService_UpdateBooking_Handler,
		},
		{
			MethodName: "DeleteBookings",
			Handler:    _BookingService_DeleteBookings_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "BookingStub/booking.proto",
}
